const GET_QUESTIONS = "GET_QUESTIONS";
const GET_DETAILS = "GET_DETAILS"
const HAS_VOTED = "HAS_VOTED";
const ADD_QUESTION = "ADD_QUESTION";
const ADD_CHOICES = "ADD_CHOICES";


export { GET_QUESTIONS, ADD_QUESTION, HAS_VOTED, GET_DETAILS, ADD_CHOICES };

// what we want to do 
